### ISSUE TITLE
Failed to Dump meta folder

### ISSUE THREAD

**Issue by Gr4ph1xZ** [dimok789/ddd#10]
When I try to dump the meta folder this happens:

<pre>
Title Dumper by Dimok

Waiting for WiiU connection...

Client 0 connected

Client 1 connected

Create path: E:/Wii U/Dump/New Super Mario Bros"/vol/meta

Open file: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/bootDrcTex.tga

Failed to open: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/bootDrcTex.tga

pFile == NULL on close

Open file: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/bootLogoTex.tga

Failed to open: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/bootLogoTex.tga

pFile == NULL on close

Open file: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/bootMovie.h264

Failed to open: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/bootMovie.h264

pFile == NULL on close

Open file: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/bootSound.btsnd

Failed to open: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/bootSound.btsnd

pFile == NULL on close

Open file: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/bootTvTex.tga

Failed to open: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/bootTvTex.tga

pFile == NULL on close

Open file: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/iconTex.tga

Failed to open: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/iconTex.tga

pFile == NULL on close

Open file: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/Manual.bfma

Failed to open: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/Manual.bfma

pFile == NULL on close

Open file: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/meta.xml

Failed to open: E:/Wii U/Dump/New Super Mario Bros"/vol/meta/meta.xml

pFile == NULL on close

Client 1 connection closed
</pre>

After I started the game, I pressed home and waited for the PC but only this happens :/

**Comment by mikahjc** [comment]
What OS are you on? It looks like it's trying to create the folder "New Super Mario Bros**"**", which is illegal because of the extra ".

**Comment by Gr4ph1xZ** [comment]
Windows
Oh thank you, that was the problem :+1: thank you :)
