### ISSUE TITLE
Dump /vol issu with mario kart 8

### ISSUE THREAD

**Issue by blairfancy** [dimok789/ddd#13]
When try to launch dump of /vol on nand game MK8 dump hang.

`./titledumper /vol ./Mario_kart_8/`

result

`Create path: ./Mario_kart_8/vntenontent`
Dont know why titledumper would dump content outside vol/ folder.

regards

**Comment by dimok789** [comment]
seems to be related to issue #7

Are you dumping on a linux system?

**Comment by blairfancy** [comment]
Correct looks same issue is there a fix to try?

**Comment by dimok789** [comment]
Yes a pull request was added and merged. Compile the last git version and it might be fixed for you. If you have trouble compiling it, let me know and I will give you a build for the OS you are on.

**Comment by blairfancy** [comment]
Good it solve the issue, dump done without crash.

**Comment by dimok789** [comment]
Thanks for confirming
