### ISSUE TITLE
<Feature Request> GUI or leaving CMD after finished dumping

### ISSUE THREAD

**Issue by Gr4ph1xZ** [dimok789/ddd#14]
Hello :)
Will there come a GUI for the titledumper? If not, is it possible to end cmd or do a PAUSE and end it wenn dumping is finished? :) because then I can make a .bat to dump only the folders I need :)

Yours sincerely,
Patrick

**Comment by mikahjc** [comment]
There's a GUI [here](http://wiiubrew.net/wiiu-tools/ddd-titledumper-gui/). As for only dumping the folders you need, have you tried specifying them when you call the program? e.g. for Smash 4: `titledumper /vol/content/movie ./Smash4` would dump just the movie files from the game.

Just realized if you want to make a .bat for only the folders you need, you probably know about specifying it in the command. Sorry! Still doesn't change that it doesn't close when the dump is finished, but one of the issues I can see is if you want to dump the /vol/meta folder, you would have to start the program on your computer after starting the game on the console. Other than that, I might take a look at implementing that.

**Comment by mikahjc** [comment]
Ok, I've created a version in my fork that will quit when you call the program with the `-q` command line option. You can get it [here](https://github.com/mikahjc/ddd/releases/tag/v0.2.5). @dimok789, if you want to check it out, I'll submit a pull request. The code isn't pretty, but it works.

**Comment by Gr4ph1xZ** [comment]
@mikahjc Hello :)
I don't know but when I dump a game (with -q) but the command prompt dosn't close after the game has been dumped.

This is the .bat 

`@ECHO OFF
set /p "pfad=Bitte den Speicher Pfad eingeben:" 
echo Der Pfad ist: %pfad%
echo Bitte an der WiiU fortfahren!
titledumper.exe /vol/code "%pfad%" -q
echo code erfolgreich gedumpt!
echo Bitte das Spiel neu starten!
titledumper.exe /vol/content "%pfad%" -q
echo content erfolgreich gedumpt!
echo Bitte das Spiel neu starten!
titledumper.exe /vol/meta "%pfad%" -q
echo meta erfolgreich gedumpt!
echo Fertig!
PAUSE`

Here is the output from the command prompt:
`Bitte den Speicher Pfad eingeben:C:\Users\patri\Downloads
Der Pfad ist: C:\Users\user\Downloads
Bitte an der WiiU fortfahren!
Title Dumper by Dimok
Waiting for WiiU connection... (press Ctrl+C to stop)
Will quit after dump.
Client 0 connected
Create path: C:/Users/user/Downloads/vol/content
Create path: C:/Users/user/Downloads/vol/content/assets
Create path: C:/Users/user/Downloads/vol/content/assets/csv
Open file: C:/Users/user/Downloads/vol/content/assets/csv/miimtnviewIblTable.csv
Read file 4 kb loaded with 19.704 kb/s
Open file: C:/Users/user/Downloads/vol/content/assets/csv/npcviewIblTable.csv
Read file 0 kb loaded with 0.000 kb/s
Open file: C:/Users/user/Downloads/vol/content/assets/drc_bg.gtx
Read file 480 kb loaded with 393.765 kb/s
Create path: C:/Users/user/Downloads/vol/content/assets/effect
Create path: C:/Users/user/Downloads/vol/content/assets/effect/system
Open file: C:/Users/user/Downloads/vol/content/assets/effect/system/default.gtx
Read file 4 kb loaded with 125.000 kb/s`
...
`Open file: C:/Users/user/Downloads/vol/content/vocal/spm.bin
Read file 2588 kb loaded with 329.304 kb/s`

here it does nothing.

The next part of the .bat won't load.

Do you have an idea what to do?

Greetings

**Comment by Gr4ph1xZ** [comment]
Sorry it was my mistake. Now it works :)
