### ISSUE TITLE
Crash when dumping "vol/code" directory of Mario Kart 8 (PAL)

### ISSUE THREAD

**Issue by JaceCear** [dimok789/ddd#2]
It is always stuck at the "vol/code/mw_shamo.rpl" file.
I tried a complete dump first, which worked fine for about an hour. Then, after it was done loading DLC data, the program tried to load the above mentioned file and froze.
Thereafter I tried only dumping "vol/code" which also crashed when hitting the same file.

_Some notes if it helps:_
**Game Version:** 4.1 (newest)
**DLC:** Both packs downloaded

Update- _and_ DLC-Data is on a USB device!

**Comment by CuriousTommy** [comment]
I am having the exact same issue as @JaceCearK1. The only difference being that I dumped the data from the physical disk and NAND (Where the DLC is installed at).

**Comment by dimok789** [comment]
Since I own that game in disc form I will try it when I find the time and see what is going wrong there.

**Comment by CuriousTommy** [comment]
@dimok789 You should talk to n1ghty, he made a private version that was able to dump the .rpl file.

**Comment by dimok789** [comment]
This is fixed with the new RC1.
