### ISSUE TITLE
Freeze while dumping specific RPX file "cafe_ITF_AppFramework_f.rpx"

### ISSUE THREAD

**Issue by Cybernatus** [dimok789/ddd#3]
DDD Title Dumper 0.2 Encounter a problem when it comes to dump a specific RPX file called "cafe_ITF_AppFramework_f.rpx" on at least 2 Japanese games I tried to backup [Just Dance Wii U Japan Edition & Yukai Watch Just Dance]. This result in a missing RPX making them impossible to launch. 
More details are available on GBATemp : https://gbatemp.net/threads/ddd-wiiu-title-dumper.418492/page-8#post-6197444  .

System : 5.4.0E
DDD V0.2

**Comment by dimok789** [comment]
Would be great if you could test it out again on v0.3 RC1. Might be one of the bugs that were fixed.

**Comment by Cybernatus** [comment]
Actually I have a received a fix version for this bug by N1ghty a short after the problem was discovered, and it worked fine. I forgot to close this ticket meanwhile and you see me sorry >_<
But to be perfectely sure DDD V0.3 is fixing stuff, I have re-done a full dump of these 2 Japanese games which resulted in a success :3

As I mentioned on GBATemp, there are few eShop games waiting to be dumped cause of the bug previous versions had. I will proceed so tomorrow and get back to you asap for feedbacks. On a side note, some dumps that have particular entitites seems to not perform well on Loadiine. N1ghty is aware of this problem and I think he has touched you a word about it (Partly related to https://github.com/dimok789/loadiine_gx2/issues/60 ).

**Comment by darkxex** [comment]
Cybernatus, is possible that you share the dump of wayforward games with problems, with fix? sorry my bad english, my native lenguage is spanish.

**Comment by Cybernatus** [comment]
Wayforward games (Shantae & Mighty) aren't fixed so far in Loadiine. In addition, you probably know that I can't share dumps here. If you wanna continue this discussion, then please contact me on GBATemp instead.

**Comment by darkxex** [comment]
sorry, i don't know, thanks.
