### ISSUE TITLE
Some files don't get dumped properly!

### ISSUE THREAD

**Issue by JaceCear** [dimok789/ddd#4]
Until now I only found files of the "/code" directory to be missing the last 5 bytes of a 0x1000 bytes sized chunk. (e.g. 0x00000FFB-0x00000FFF; 0x00001FFB-0x00001FFF...)
**Occured with v0.3_RC1**, not with v0.2!

**Comment by dimok789** [comment]
Thanks for the report! This is actually a bad bug. Does this happen with every RPX/RPL or just some specific?

Also you talk about a 0x1000 bytes chunk what kind of file is it? RPX/RPL? and how can I reproduce that bug?

**Comment by dimok789** [comment]
Ok I found the bug and fixed it with RC2. Please test and confirm it working for you too.

**Comment by JaceCear** [comment]
It was RPL and RPX.
The dump looks fine now, but the game crashed on the boot-screen after dumping the files.
[Mario Kart 8 PAL | Only dumped /vol/code folder]

**Comment by dimok789** [comment]
Oh it crashed? Hmm I will try it. I got the game.

**Comment by dimok789** [comment]
You are right it hangs after the dump. What the hell...

**Comment by dimok789** [comment]
Ok now it runs. https://github.com/dimok789/ddd/releases/tag/v0.3_RC3

**Comment by JaceCear** [comment]
Looks good to me! :+1:

**Comment by dimok789** [comment]
Great. Thanks.
